### ISSUE TITLE
`dump` on server clears cache against documentation suggestion.

### ISSUE THREAD

**Issue by indifferentghost** [muratgozel/metapatcher#11]
The [documentation](https://github.com/muratgozel/metapatcher?tab=readme-ov-file#server-side-usage) states:
> This property decides if the library should inject tags or collect them in memory. So, when you run the library in a non-browser environment, they will be kept in memory.

The [code](https://github.com/muratgozel/metapatcher/blob/master/src/index.ts#L510-L516) doesn't seem to reflect this.

We can just add a check in the code if it's in the browser and go from there:
```js
    dump(): string {
        const data = this.memory.join('\n')

        // if we're in the browser, reset memory
        if (this.isDomAvailable) this.memory = []

        return data
    }
```

**Comment by indifferentghost** [comment]
Current workaround is using memory directly: `metapatcher.memory.join('\n')`.

**Comment by muratgozel** [comment]
There should certainly be a check for dom while calling dump. Thank you for the PR @indifferentghost I will merge it shortly.

**Comment by muratgozel** [comment]
@indifferentghost I understand you use `.dump()` server-side as it should be but what problem do you have with its clearing cache? Server renders happen once per request and so it just dumps once and clears itself. Can you elaborate the problem here?

**Comment by indifferentghost** [comment]
Hey, I'm using it as middleware for keeping head state across endpoints, many of these use the same head, but a few of them are different. It's useful for me to keep state rather than a finished dump.

**Comment by indifferentghost** [comment]
I don't see why it shouldn't though.

**Comment by muratgozel** [comment]
It's just because it's meant to be used in server side, i mean the dump method. we are able to use html dom like a memory in browsers so i would like to keep it as much as possible. anyway, i released the new version, it should be fixed now. thank you for the collaboration @indifferentghost
