### ISSUE TITLE
`prefixId` should reset after update

### ISSUE THREAD

**Issue by indifferentghost** [muratgozel/metapatcher#13]
Upon setting a custom `prefixId` a reset is needed or previously created tags.

In order to get a full reset after a custom `prefixId` we needed to reset the msapplicationconfig called in the constructor:

```js
metapatcher.idPrefix = 'okr';
metapatcher.setMsApplicationConfig('none');
```

if you don't the original set remains.
```html
<meta id="metapatcher-msapplication-config" name="msapplication-config" content="none">
```

**Comment by indifferentghost** [comment]
It could be allowed by pass a config through the `Metapatcher` class.

**Comment by indifferentghost** [comment]
Anything that creates a tag needs to be reset for example:
```js
metapatcher.configure();
metapatcher.idPrefix = 'whatever';
```
would still have the previous prefix.

I'm getting a hunch that long term it would be better to generate these all on a `.dump()` command or something similar.

**Comment by muratgozel** [comment]
As the library is a singleton, i think it's best to have a method such as `updateIdPrefix()` and it updates all the existing patched dom node elements and also sets `.idPrefix` when called.

> I'm getting a hunch that long term it would be better to generate these all on a `.dump()` command or something similar.

I understand this and decided against it until we really need to keep the data in `.memory` in browser env. Let's see how it evolves.

**Comment by muratgozel** [comment]
I've added a settings object option to the configure method. (v4.1) Refer to readme please and let me know if that doesn't work for you.
